spring.application.name=Vehical-Rental-Service-Platform
spring.mvc.view.prefix=
spring.mvc.view.suffix=
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true
